import { test, describe } from 'node:test'
import assert from 'node:assert/strict'

import {
  COMPACT,
  JUDGE_SYSTEM,
  KEEP,
  RECENT_ACTIONS,
  RECENT_REQUESTS,
  RECENT_SAYINGS,
  REQUEST_LINE,
  STEP_LIMIT,
  TOUCH_LIMIT,
  beforeStep,
  conversationLines,
  acts,
  isRequest,
  judgeable,
  judgePrompt,
  readReply,
  saysCompact,
  taskList,
  touched,
} from '../hooks/judge.ts'

type Message = Parameters<typeof conversationLines>[0][number]

function person(text: string): Message {
  return { role: 'user', text, toolUses: [] }
}

function ran(tool: string, input: Record<string, unknown>, text = ''): Message {
  return { role: 'assistant', text, toolUses: [{ tool_use_id: tool, tool, input, text: 'OUTPUT OF THE CALL' }] }
}

function said(text: string): Message {
  return { role: 'assistant', text, toolUses: [] }
}

function output(text: string, id = 't'): Message {
  return { role: 'user', text: '', toolUses: [], toolResults: [{ tool_use_id: id, text, isError: false }] }
}

const step = (text: string, calls: { name: string; input: unknown }[] = [{ name: 'Bash', input: { command: 'ls' } }]) => ({ text, calls })

describe('isRequest', () => {
  test('what the person typed is a request', () => {
    assert.equal(isRequest(person('fix issue 3')), true)
  })

  test('messages nobody typed are not', () => {
    for (const text of [
      '<task-notification>\n<task-id>a1</task-id>\n<status>completed</status>',
      'The taskcut plugin sent a message:\nContinue.',
      '<local-command-stdout>(no content)</local-command-stdout>',
      'Caveat: The messages below were generated by the user while running local commands. DO NOT respond',
      '[Request interrupted by user]',
      '  ',
    ]) {
      assert.equal(isRequest(person(text)), false, text)
    }
    assert.equal(isRequest(output('4 passed')), false)
    assert.equal(isRequest(said('done')), false)
  })
})

describe('touched', () => {
  test('a file call is the tool and the file', () => {
    assert.equal(touched('Edit', { file_path: 'a.py', old_string: 'x', new_string: 'y' }), 'Edit a.py')
    assert.equal(touched('Write', { file_path: 'b.py', content: 'SECRET'.repeat(100) }), 'Write b.py')
  })

  test('a command is what it says it does, or its first words', () => {
    assert.equal(touched('Bash', { command: 'pytest -q', description: 'Run the tests' }), 'Bash: Run the tests')
    assert.equal(touched('Bash', { command: 'pytest -q\n  tests/a.py' }), 'Bash: pytest -q tests/a.py')
    assert.ok(touched('Bash', { command: 'x'.repeat(TOUCH_LIMIT * 3) }).length < TOUCH_LIMIT + 20)
  })

  test('any other call is its input, cut short', () => {
    assert.equal(touched('Skill', { skill: 'polish-zh' }), 'Skill: {"skill":"polish-zh"}')
    assert.ok(touched('Agent', { prompt: 'p'.repeat(1000) }).length < TOUCH_LIMIT + 20)
  })
})

describe('conversationLines', () => {
  test('keeps what the person asked and what the assistant touched, in order', () => {
    const lines = conversationLines([person('fix issue 3'), ran('Bash', { command: 'pytest', description: 'Run the tests' }), person('thanks')])
    assert.deepEqual(lines, ['Person: fix issue 3', 'Assistant ran Bash: Run the tests', 'Person: thanks'])
  })

  test('never any tool output', () => {
    const text = conversationLines([person('go'), ran('Bash', { command: 'cat x' }), output('SECRET FILE CONTENT')]).join('\n')
    assert.ok(!text.includes('SECRET FILE CONTENT'))
    assert.ok(!text.includes('OUTPUT OF THE CALL'))
  })

  test('never a call in full', () => {
    const text = conversationLines([ran('Write', { file_path: 'a.py', content: 'THE WHOLE FILE' })]).join('\n')
    assert.equal(text, 'Assistant ran Write a.py')
  })

  test('leaves out read-only lookups', () => {
    const lines = conversationLines([ran('Read', { file_path: 'a.py' }), ran('Grep', { pattern: 'x' }), ran('Edit', { file_path: 'a.py' })])
    assert.deepEqual(lines, ['Assistant ran Edit a.py'])
  })

  test('the first request and the latest few whole, the rest a line each', () => {
    const long = (i: number) => `request ${i}: ${'z'.repeat(1000)} END ${i}`
    const lines = conversationLines(Array.from({ length: 10 }, (_, i) => person(long(i))))
    const whole = [0, ...Array.from({ length: RECENT_REQUESTS }, (_, i) => 9 - i)]
    for (let i = 0; i < 10; i++) {
      const line = lines[i]!
      if (whole.includes(i)) assert.equal(line, `Person: ${long(i)}`)
      else assert.ok(line.startsWith(`Person (shortened): request ${i}`) && line.length < REQUEST_LINE + 40, line)
    }
  })

  test('only the latest of what the assistant said, and says how much it left out', () => {
    const lines = conversationLines(Array.from({ length: RECENT_SAYINGS + 5 }, (_, i) => said(`said ${i}`)))
    assert.equal(lines[0], '(5 earlier assistant messages left out)')
    assert.equal(lines[1], 'Assistant: said 5')
    assert.equal(lines.length, RECENT_SAYINGS + 1)
  })

  test('only the latest of what the assistant touched', () => {
    const lines = conversationLines(Array.from({ length: RECENT_ACTIONS + 5 }, (_, i) => ran('Edit', { file_path: `f${i}.py` })))
    assert.equal(lines.length, RECENT_ACTIONS)
    assert.equal(lines[0], 'Assistant ran Edit f5.py')
  })

  test('messages nobody typed are left out', () => {
    const lines = conversationLines([person('do A and B'), person('The taskcut plugin sent a message:\nContinue.'), person('<task-notification>x</task-notification>')])
    assert.deepEqual(lines, ['Person: do A and B'])
  })

  test('a compaction summary reads as one, not as a request', () => {
    const summary = `This session is being continued from a previous conversation that ran out of context. ${'s'.repeat(5000)} Issue 20 is done.`
    const [line] = conversationLines([person(summary)])
    assert.ok(line!.startsWith('Summary of the conversation before it was compacted: This session'))
    assert.ok(line!.endsWith('Issue 20 is done.'))
    assert.ok(line!.length < 3_000)
  })
})

describe('taskList', () => {
  test('the list as TodoWrite last wrote it', () => {
    const write = (statuses: string[]) => ran('TodoWrite', { todos: statuses.map((status, i) => ({ content: `task ${i + 1}`, status })) })
    const list = taskList([write(['in_progress', 'pending']), write(['completed', 'in_progress'])], step('go'))
    assert.deepEqual(list, ['[done] task 1', '[doing] task 2'])
  })

  test('the tasks TaskCreate made, as TaskUpdate left them', () => {
    const list = taskList(
      [ran('TaskCreate', { subject: 'fix A' }), ran('TaskCreate', { subject: 'fix B' }), ran('TaskCreate', { subject: 'drop C' }), ran('TaskUpdate', { taskId: '1', status: 'completed' }), ran('TaskUpdate', { taskId: '3', status: 'deleted' })],
      step('A done; on to B', [{ name: 'TaskUpdate', input: { taskId: '2', status: 'in_progress' } }]),
    )
    assert.deepEqual(list, ['[done] fix A', '[doing] fix B'])
  })

  test('nothing when the assistant keeps no list', () => {
    assert.deepEqual(taskList([ran('Bash', { command: 'ls' })], step('go')), [])
  })
})

describe('beforeStep', () => {
  const judged = step('task 1 is done; now task 2', [{ name: 'Bash', input: { command: 'pytest' } }])

  test('leaves out the step when the transcript already holds it, as one message', () => {
    const messages = [person('go'), ran('Bash', { command: 'pytest' }, 'task 1 is done; now task 2')]
    assert.deepEqual(beforeStep(messages, judged), [person('go')])
  })

  test('keeps everything when the transcript does not hold it yet', () => {
    const messages = [person('go'), ran('Bash', { command: 'ls' })]
    assert.equal(beforeStep(messages, judged), messages)
  })

  // What `$.session.messages()` holds when the step is judged, on 2.1.280: the
  // response a block at a time, and the results of calls that have already run.
  const earlier = [person('go'), ran('Bash', { command: 'ls' }), output('a.txt')]

  test('leaves out a step held a block at a time', () => {
    const messages = [...earlier, said('task 1 is done; now task 2'), ran('Bash', { command: 'pytest' })]
    assert.deepEqual(beforeStep(messages, judged), earlier)
  })

  test('leaves out the results of its calls when they have already run', () => {
    const messages = [...earlier, said('task 1 is done; now task 2'), ran('Bash', { command: 'pytest' }), output('3 passed', 'Bash')]
    assert.deepEqual(beforeStep(messages, judged), earlier)
  })

  test('leaves out a step of several calls, their results after them', () => {
    const two = step('both', [{ name: 'Read', input: { file_path: 'a' } }, { name: 'Bash', input: { command: 'ls' } }])
    const messages = [person('go'), said('both'), ran('Read', { file_path: 'a' }), ran('Bash', { command: 'ls' }), output('A', 'Read'), output('B', 'Bash')]
    assert.deepEqual(beforeStep(messages, two), [person('go')])
  })

  test('leaves out a step that only calls', () => {
    const quiet = step('', [{ name: 'Bash', input: { command: 'pytest' } }])
    assert.deepEqual(beforeStep([...earlier, ran('Bash', { command: 'pytest' })], quiet), earlier)
  })

  test('keeps the results of the step before it', () => {
    const messages = [...earlier, said('task 1 is done; now task 2')]
    assert.equal(beforeStep(messages, judged), messages)
  })

  test('keeps everything when something else comes between the step and the end', () => {
    const messages = [...earlier, said('task 1 is done; now task 2'), ran('Bash', { command: 'pytest' }), person('stop')]
    assert.equal(beforeStep(messages, judged), messages)
  })

  test('keeps everything when a result is not of the step\'s calls', () => {
    const messages = [...earlier, said('task 1 is done; now task 2'), ran('Bash', { command: 'pytest' }), output('?', 'Other')]
    assert.equal(beforeStep(messages, judged), messages)
  })

  test('the step is not read twice in the prompt', () => {
    const messages = [...earlier, said('task 1 is done; now task 2'), ran('Bash', { command: 'pytest' }), output('3 passed', 'Bash')]
    const text = judgePrompt(messages, judged)
    assert.equal(text.split('task 1 is done; now task 2').length - 1, 1)
    assert.equal(text.split('Assistant ran Bash').length - 1, 1)
  })
})

describe('judgeable', () => {
  test('a step that says nothing is never a boundary, so it is not asked about', () => {
    assert.equal(judgeable(step('')), false)
    assert.equal(judgeable(step('  \n')), false)
    assert.equal(judgeable(step('Task 1 done. Now task 2.')), true)
  })
})

describe('acts', () => {
  test('a call that changes something acts; a lookup does not', () => {
    assert.equal(acts([{ name: 'Read' }, { name: 'Grep' }]), false)
    assert.equal(acts([{ name: 'Read' }, { name: 'Write' }]), true)
    assert.equal(acts([]), false)
  })
})

describe('judgePrompt', () => {
  test('carries the request, the step and its calls, the step last', () => {
    const text = judgePrompt(
      [person('fix issue 3'), ran('Bash', { command: 'pytest', description: 'Run the tests' })],
      step('issue 3 is fixed; on to issue 4', [{ name: 'Edit', input: { file_path: 'b.py' } }]),
    )
    for (const expected of ['Person: fix issue 3', 'Assistant ran Bash: Run the tests', 'issue 3 is fixed; on to issue 4', 'Calls Edit: {"file_path":"b.py"}']) {
      assert.ok(text.includes(expected), expected)
    }
    assert.ok(text.indexOf('Run the tests') < text.indexOf('issue 3 is fixed'))
  })

  test('reads the step once, when the transcript already holds it', () => {
    const calls = [{ name: 'Edit', input: { file_path: 'b.py' } }]
    const text = judgePrompt([person('go'), ran('Edit', { file_path: 'b.py' }, 'issue 3 is fixed')], step('issue 3 is fixed', calls))
    assert.ok(!text.includes('Assistant ran Edit b.py'))
    assert.equal(text.split('issue 3 is fixed').length, 2)
  })

  test('shows the task list between the conversation and the step', () => {
    const text = judgePrompt([person('do A, B'), ran('TodoWrite', { todos: [{ content: 'A', status: 'completed' }, { content: 'B', status: 'pending' }] })], step('A done; on to B'))
    assert.ok(text.indexOf("--- the assistant's task list") < text.indexOf('--- latest step'))
    assert.match(text, /\[done\] A\n\[todo\] B/)
  })

  test('does not grow with the work, only with what the person says', () => {
    const work = (n: number) => [person('fix all of ISSUES.md'), ...Array.from({ length: n }, () => [ran('Bash', { command: 'pytest -q', description: 'Run the tests' }, 'Checking.'), output('ok')]).flat()]
    // The same but for the count of what the assistant said that was left out.
    const [short, long] = [judgePrompt(work(50), step('go on')), judgePrompt(work(5000), step('go on'))]
    assert.equal(long.replace(/\d+ earlier/, 'N earlier'), short.replace(/\d+ earlier/, 'N earlier'))
  })

  test('keeps the end of a long step, where a model says whether it is done', () => {
    const text = judgePrompt([], step('x'.repeat(STEP_LIMIT * 2) + 'Now task 3.'))
    assert.match(text, /Now task 3\./)
  })

  test('says so when there is no text', () => {
    assert.match(judgePrompt([], step('')), /\(no text\)/)
  })

  test('the question names both answers', () => {
    assert.ok(JUDGE_SYSTEM.includes(COMPACT) && JUDGE_SYSTEM.includes(KEEP))
  })
})

describe('readReply', () => {
  test('reads the text $.model.complete resolved up to 2.1.278', () => {
    assert.deepEqual(readReply('It moves on.\nNEXT'), { text: 'It moves on.\nNEXT' })
  })

  test('reads the result it resolves from 2.1.280', () => {
    const usage = { input_tokens: 1, output_tokens: 1, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 }
    assert.deepEqual(readReply({ isAnswered: true, text: 'SAME', usage }), { text: 'SAME' })
    assert.deepEqual(readReply({ isAnswered: false, reason: 'api-error', status: 529, error: 'overloaded', usage }), { reason: 'api-error 529 overloaded' })
    assert.deepEqual(readReply({ isAnswered: false, reason: 'api-error', status: null, error: 'unknown', usage }), { reason: 'api-error unknown' })
    assert.deepEqual(readReply({ isAnswered: false, reason: 'aborted', usage }), { reason: 'aborted' })
  })

  test('anything else is no reply, never a verdict', () => {
    for (const odd of [undefined, null, 42, {}, { isAnswered: true }, { text: 'NEXT' }]) {
      assert.ok('reason' in readReply(odd), JSON.stringify(odd))
    }
  })
})

describe('saysCompact', () => {
  test('reads the verdict off the last line', () => {
    assert.equal(saysCompact('Task 2 is done and task 3 needs none of it.\nCOMPACT'), true)
    assert.equal(saysCompact('The next step needs what the query printed.\nKEEP'), false)
  })

  test('ignores the emphasis a model puts round the word', () => {
    assert.equal(saysCompact('Nothing open needs the earlier output.\n**COMPACT**'), true)
    assert.equal(saysCompact('Nothing open needs the earlier output.\n"Compact."'), true)
  })

  test('a verdict mentioned in the reasoning is not the verdict', () => {
    assert.equal(saysCompact('It is not yet safe to COMPACT.\nKEEP'), false)
  })

  test('no answer is not a moment to compact', () => {
    assert.equal(saysCompact(''), false)
    assert.equal(saysCompact('I cannot tell.'), false)
  })
})
